version: '2'
services:
  mysql:
    container_name: bi_mysql
    extends:
      file: mysql.yml
      service: mysql
    networks:
      - bi-net
  minio:
    container_name: bi_minio
    extends:
      file: minio.yml
      service: minio
    networks:
      - bi-net
  chroma:
    container_name: bi_chroma
    image: crpi-gxv0234hwyx1jbhm.cn-beijing.personal.cr.aliyuncs.com/qxr777/chroma:1.0.8
    extends:
      file: chroma.yml
      service: chroma
    networks:
      - bi-net
  bi_building_inspector:
    image: crpi-gxv0234hwyx1jbhm.cn-beijing.personal.cr.aliyuncs.com/qxr777/building-inspector:1.0
    container_name: bi_building_inspector
    ports:
      - "8090:80"
    restart: always
    networks:
      - bi-net
    depends_on:
      - mysql
      - minio
  bi_building_inspector_ai:
    image: crpi-gxv0234hwyx1jbhm.cn-beijing.personal.cr.aliyuncs.com/qxr777/building-inspector-ai:1.0
    container_name: bi_building_inspector_ai
    ports:
      - "8081:8081"
    restart: always
    networks:
      - bi-net
    depends_on:
      - mysql
      - minio
      - bi_building_inspector
      - chroma
networks:
  bi-net:
