-- 由 Excel 自动生成：bi_template_object 导入脚本（自增ID，仅追加）
SET NAMES utf8mb4;
START TRANSACTION;

-- 顶层：梁桥-整体式板
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-整体式板', 0, '0', 1, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.4500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('实心板/空心板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 85.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 15.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：梁桥-装配式实心板
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-装配式实心板', 0, '0', 2, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.4500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('实心板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('铰缝', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 10.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：梁桥-装配式空心板
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-装配式空心板', 0, '0', 3, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.4500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('空心板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('铰缝', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 10.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：梁桥-装配式组合箱梁及肋梁
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-装配式组合箱梁及肋梁', 0, '0', 4, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.4500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横隔板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 25.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：梁桥-整体现浇箱梁
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-整体现浇箱梁', 0, '0', 5, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('箱梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 75.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 25.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：梁桥-悬臂施工箱梁
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-悬臂施工箱梁', 0, '0', 6, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('箱梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横隔板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 15.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：梁桥-钢及钢混组合梁
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('梁桥-钢及钢混组合梁', 0, '0', 7, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 25.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 10.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 15.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-实腹式板拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-实腹式板拱', 0, '0', 8, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主拱圈', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 70.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('拱上侧墙', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-空腹式圬工板拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-空腹式圬工板拱', 0, '0', 9, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主拱圈', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱墩', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 15.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱圈或桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 30.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 20.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-空腹式钢筋混凝土板拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-空腹式钢筋混凝土板拱', 0, '0', 10, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主拱圈', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 55.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱墩', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱圈或桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-肋拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-肋拱', 0, '0', 11, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('拱肋', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 45.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 15.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱墩', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱圈或桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 25.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-箱形拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-箱形拱', 0, '0', 12, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('拱箱', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 55.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱墩', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱圈或桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-双曲拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-双曲拱', 0, '0', 13, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主拱圈', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 10.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱墩', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 20.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('腹拱圈或桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-桁架拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-桁架拱', 0, '0', 14, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桁架拱片', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 25.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：拱桥-刚架拱
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('拱桥-刚架拱', 0, '0', 15, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('刚架拱片', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 25.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：组合体系拱桥-无系杆
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('组合体系拱桥-无系杆', 0, '0', 16, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('拱肋', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 10.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('吊索或立柱', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横梁及桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 25.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：组合体系拱桥-柔性系杆
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('组合体系拱桥-柔性系杆', 0, '0', 17, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.6000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('拱肋', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 25.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('系杆索', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 10.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('吊索或立柱', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 30.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横梁及桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 5, '0', '0', 15.0000, '5', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.2000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：组合体系拱桥-刚性系杆
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('组合体系拱桥-刚性系杆', 0, '0', 18, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('拱肋', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 40.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('系杆', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 10.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('横向联系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 10.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('吊索或立柱', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 25.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面板', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 5, '0', '0', 15.0000, '5', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('翼墙、锥坡、护坡', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 15.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());

-- 顶层：悬索桥-自锚式悬索桥
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('悬索桥-自锚式悬索桥', 0, '0', 19, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.6000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('加劲梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 20.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('吊索及索夹', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主缆', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 20.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('索塔及索鞍', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('锚固系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 5, '0', '0', 10.0000, '5', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('约束体系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 6, '0', '0', 10.0000, '6', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.2500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 40.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('照明、标志', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 10.0000, '4', 'admin', NOW());

-- 顶层：悬索桥-地锚式悬索桥
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('悬索桥-地锚式悬索桥', 0, '0', 20, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.5000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('加劲梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 20.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('吊索及索夹', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 25.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主缆', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('索塔及索鞍', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 20.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('约束体系', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 5, '0', '0', 10.0000, '5', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.3500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 30.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('锚碇及锚固系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 50.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 40.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('照明、标志', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 10.0000, '4', 'admin', NOW());

-- 顶层：斜拉桥-斜拉桥
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('斜拉桥-斜拉桥', 0, '0', 21, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.6000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 30.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('斜拉索', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 35.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('索塔', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 10.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.2500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 40.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('照明、标志', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 10.0000, '4', 'admin', NOW());

-- 顶层：斜拉桥-部分斜拉桥
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, create_by, create_time) VALUES ('斜拉桥-部分斜拉桥', 0, '0', 22, '0', '0', 'admin', NOW());
SET @top_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('桥面系', @top_id, CONCAT('0,', @top_id), 1, '0', '0', 0.1000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥面铺装', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 50.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('伸缩装置', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('护栏及人行道', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('上部结构', @top_id, CONCAT('0,', @top_id), 2, '0', '0', 0.6000, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('主梁', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 35.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('斜拉索', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 30.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('索塔', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 25.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('支座', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 10.0000, '4', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('下部结构', @top_id, CONCAT('0,', @top_id), 3, '0', '0', 0.2500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('桥墩或桥台', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 60.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('墩台基础', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 40.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, impact_factor, create_by, create_time) VALUES ('附属构造', @top_id, CONCAT('0,', @top_id), 4, '0', '0', 0.0500, 'admin', NOW());
SET @struct_id := LAST_INSERT_ID();
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('排水系统', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 1, '0', '0', 40.0000, '1', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('河床及调治构造物', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 2, '0', '0', 20.0000, '2', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('其他附属设施', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 3, '0', '0', 30.0000, '3', 'admin', NOW());
INSERT INTO bi_template_object (name, parent_id, ancestors, order_num, status, del_flag, weight, category_i, create_by, create_time) VALUES ('照明、标志', @struct_id, CONCAT('0,', @top_id, ',', @struct_id), 4, '0', '0', 10.0000, '4', 'admin', NOW());

COMMIT;